### ISSUE TITLE
Logo/icon

### ISSUE THREAD

**Issue by jnpoJuwan** [dec32/Ajemi#13]
the logo for the project would be better as a black and white logo as opposed to the current coloured one. this matches to other keyboard inputs in Windows. fonts like Fairfax HD would work well for this.

![Input method for English](https://github.com/dec32/Ajemi/assets/48970145/d0fa55e9-da0c-4cc0-9e84-fe3e05db0d02)
![Input method editor for Chinese (Pinyin)](https://github.com/dec32/Ajemi/assets/48970145/dd9b15c5-ff05-426d-9963-d53f4d4c367d)
![Ajemi input method editor](https://github.com/dec32/Ajemi/assets/48970145/a538f9b6-3be6-4cbb-b7fe-bd4e649d31d6)

**Comment by dec32** [comment]
Updated. It now uses a monochrome tray icon.

![](https://github.com/dec32/Ajemi/assets/56337978/f483192e-8e22-446f-9798-f23dae5a4f41)
