### ISSUE TITLE
[request] ideographic space

### ISSUE THREAD

**Issue by pandaqwanda** [dec32/Ajemi#15]
please add the ideographic space symbol (u+3000, `　`) to ajemi
i use it in my sitelen pona writing and usually have to copypaste it from a unicode chart, a searchchar window or similar
it can be bound to the `=`/`+` key and/or there can be a line in the config file for whether ajemi converts regular spaces to ideographic ones

**Comment by dec32** [comment]
Added. <kbd>Space</kbd> is now mapped to `u+3000` when there's no composition going on.
