### ISSUE TITLE
Problem typing Sitelen Pona variants in nasin Ajemi

### ISSUE THREAD

**Issue by yan-Mayeka** [dec32/Ajemi#16]
Unlike nasin AHK, you cannot type glyph variants. Even if you tried by pressing numbers 1-8, it just selects a suggested character. I don't know if not having variants is intentional or not, but I feel like it should be able to type variants too. What am I missing?

**Comment by dec32** [comment]
It is intentional because the glyph variants are not defined in UCSUR and most fonts don't support them.
