### ISSUE TITLE
Writing compound characters

### ISSUE THREAD

**Issue by l1minalspace** [dec32/Ajemi#17]
I've recently tried your IME and noticed a few moments relating to combined glyphs, that could be realized better:
1. When writing a compound character, I should be able to see the two words i've written in ASCII characters before hitting space. So currently, for example, when after writing 'toki' I type '-' to join with 'pona', 'toki-' becomes a sitelen pona character instead of waiting for me to write 'pona', hit space and only then to make those into a tp character. I think the current implementation lowers the comprehension a bit.
2. It would be very helpful if the options included possible versions of compound characters depending on words written. So you would write 'tokipona', hit space and the first option would be two separate characters and the second - a compound one.
3. I should select options from the list not with numbers (which btw didn't work for me for some reason), but rather with space. Like hitting space two times will select the second option.

**Comment by dec32** [comment]
1. Will implement it.
2. The support for compound glyphs varies from font to font. Some support many of them while some support none. People's preference on compound glyph also varies greatly. Some use them excessively while some doen't use them at all. To make the situation even more complicated, there're three ways (stacking, scaling and default) that SP glyphs can be compounded. Taking all these facts into consideration, coming up with a list of "possible versions of compound characters" is quite difficult. For now I do not plan to implment that.
3. As for candidate selecting, please open new issues for that.

**Comment by dec32** [comment]
1. Will implement it.
2. The support for compound glyphs varies from font to font. Some support many of them while some support none. People's preference on compound glyphs also varies greatly. Some use them excessively while some doen't use them at all. To make the situation even more complicated, there're three ways (stacking, scaling and default) that SP glyphs can be compounded. Taking all these facts into consideration, coming up with a list of "possible versions of compound characters" is quite difficult. For now I do not plan to implment that.
3. As for candidate selecting, please open new issues for that.

**Comment by dec32** [comment]
1. Will implement it.
2. The support for compound glyphs varies from fonts to fonts. Some support many of them while some support none. People's preference on compound glyphs also varies greatly. Some use them almost excessively while some don't use them at all. To make the situation even more complicated, there're three ways (stacking, scaling and default) that SP glyphs can be compounded. Taking all these facts into consideration, coming up with a list of "possible versions of compound characters" is quite difficult. For now I do not plan to implment that.
3. As for candidate selecting, please open new issues for that.

**Comment by dec32** [comment]
Implemented.
