### ISSUE TITLE
[Suggestion] Do not extend glyphs by default

### ISSUE THREAD

**Issue by gregdan3** [dec32/ajemi#19]
One of the first things I see new Ajemi users do is disable extended glyphs. This isn't entirely because  they don't want extended glyphs, though it is often that. But it also happens because, unless you're typing entire sentences at once, committing an extended glyph is somewhat confusing:
- You can only see the first pair character, so deleting a committed statement with an extension appears to do nothing at first.
- You must commit once you've finished writing the contents of your extended glyph- if you continue to type, the suggestion cannot determine where the extended glyph should end, so the first suggested commit will be incorrect. You can only commit word by word as an alternative, which will lose the extended glyph anyway. Try out "sina sona ala sona e ni"
- Some of the extensions are applied improperly (and maybe this bit should be a bug report): try "sina sona ala e ni": the back-extension of ala applies, but that particular extension is only used if asking a question (and it's rare at that)

Also, most fonts have incomplete support for all the extensions Ajemi has built in. For example:

![image](https://github.com/dec32/ajemi/assets/28300107/28b5741b-2f23-4574-85a7-b1416d667759)

This is the latest version of nasin nanpa. For context though, it does  It supports tawa, lon, and kepeken, but doesn't support sama or tan (although ajemi does not do these either).

**Comment by dec32** [comment]
They are off by default now.
