### ISSUE TITLE
[Feature request] Keyboard layout setting

### ISSUE THREAD

**Issue by SarahIsWeird** [dec32/ajemi#21]
Hi, I love Ajemi! It took a lot of work to make it use the QWERTY keyboard layout though, instead of the German QWERTZ. Someone I know wants to use Ajemi as well, but can't use its advanced features like `^`, since their default layout is AZERTY. Would there be a possibility to specify the layout Ajemi inherits in its configuration? Thank you :)

**Comment by dec32** [comment]
Fixed. Users can decide which keyboard layout to use when installing now.
