### ISSUE TITLE
Can't see sitelen pona while I'm typing

### ISSUE THREAD

**Issue by CrawlyMonster** [dec32/Ajemi#3]
When I try to use the input method in Microsoft Word, it won't let me write in the Nishiki Teki font, only "DengXian", so the sitelen pona characters don't display. Once I have written the words, I can then change the font to Nishiki Teki and it still works, but I can't see the words while I'm typing.
<img width="160" alt="Screenshot 2024-01-07 143107" src="https://github.com/dec32/Ajemi/assets/128271234/b5515526-e378-4a96-9134-f912daae5bbe">
<img width="133" alt="Screenshot 2024-01-07 143123" src="https://github.com/dec32/Ajemi/assets/128271234/9c66fadd-c0e5-4937-98c1-5d9eaf6fa91c">
This may be a problem with Word or the font, but I'm not sure.

**Comment by dec32** [comment]
I've tested a few fonts. Most likely a problem with MS Word. It's very stubborn on changing your fonts.

**Comment by dec32** [comment]
Try out the standalone version:

https://github.com/dec32/Ajemi/releases/download/nightly/ajemi-installer_x64.exe

It works well with MS Word.

![](https://github.com/dec32/Ajemi/assets/56337978/3fa3bceb-586d-4d47-96ea-4a365c295c5f)
