### ISSUE TITLE
[Windows 11] Cannot use Ajemi input method while focused on Discord

### ISSUE THREAD

**Issue by gregdan3** [dec32/Ajemi#5]
If you attempt to switch IME with your keyboard shortcut, it won't change. If you change it to Ajemi before focusing on Discord, it will switch to your default on focusing Discord, and switch back to Ajemi when focusing elsewhere.

I thought it might be an Electron issue, but I can switch to Ajemi in Obsidian, so I'm unsure. 

This seems to have some precedent as a Discord specific issue though:

https://www.reddit.com/r/discordapp/comments/6htwc2/microsoft_ime_and_discord_weirdness/
https://www.reddit.com/r/Windows10/comments/g39mrp/cant_switch_to_typing_with_hiragana_with_japanese/
https://www.reddit.com/r/discordapp/comments/96fc0v/why_input_language_change_doesnt_work_on_discord/

Which is concerning.

**Comment by dec32** [comment]
Just fixed. The download link is also updated. It turns out to be some 32-bit compatibility issue. 

![discord](https://github.com/dec32/Ajemi/assets/56337978/5547d060-a5b8-4176-8968-ca241a6b9419)

**Comment by dec32** [comment]
Just fixed. The download link is updated. It turns out to be a 32-bit program compatibility issue.

![](https://github.com/dec32/Ajemi/assets/56337978/601eb70b-6da6-4528-811c-30e74609ad74)
