### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by jnpoJuwan** [dec32/Ajemi#7]
how may I customise my keyboard now? after since the change from RIME to this, I don't know how to customise it, such as letters keys and such? something else that is not nice is when it automically adds containers and extenders, most people do *not* want that, so that would be good to have a way to disable it. I also want to ask for a friend who wishes to use this IME, but they are more accoustumed to the AZERTY keyboard and doesn't want to change how they type.

**Comment by dec32** [comment]
Support for such customization is planned but not yet implemented. So maybe stick to RIME for now.

The configuration files and documentation are hosted [here](https://github.com/dec32/Ajemi/releases/tag/rime-schema).

**Comment by jnpoJuwan** [comment]
ahh alright, that's alright

**Comment by jnpoJuwan** [comment]
on another note, just to not have to make another issue, may you change the icon from the coloured toki pona logo to something simpler, such as a black-and-white icon of it in a font like Fairfax HD, as that would fit in better with icons in Windows for example

**Comment by jnpoJuwan** [comment]
woo, it works! however please set the default preference for autoextend to `false`

**Comment by jnpoJuwan** [comment]
actually! another thing that would be useful is having a different configuration for long pi and other extended glyphs
long pi is a very common feature compared to other glyphs so it makes sense to differentiate that, as I would want

**Comment by dec32** [comment]
The configuration for long pi is now separated. You can use

```Toml
[behavior]
long_pi = true
long_glyph = false
```

to enable long pi while leaving other long glyphs disabled.

**Comment by dec32** [comment]
The input method can detects non-qwerty keyboard layouts and applys them automatically now.
